site_name: shellai
site_description: "Main documentation for shellai project"
repo_url: https://github.com/xgeeks-geekathon/shellai.git
edit_uri: edit/master/docs

# plugins:
#   - techdocs-core

# For sidebar navigation
nav:
  - Getting Started: "index.md"
